apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "hello-kubernetes.name" . }}
spec:
  rules:
    - host: {{ .Values.ingress.path }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{- include "hello-kubernetes.labels" . | nindent 4 }}
              servicePort: {{ .Values.service.port }}
