#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: {{ include "hello-kubernetes.name" . }}-ingress
#spec:
#  rules:
#    - host: {{ .Values.ingress.hostPath }}
#      http:
#        paths:
#          - path: /
#            backend:
#              serviceName: {{ include "hello-kubernetes.name" . }}
#              servicePort: {{ .Values.service.port }}
